
server:
  port: 8888
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
zuul:
  routes:
    api:
      path: /v1/**
      serviceId:  api
