
server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout:  5000
logging:
  level:
    cn.edu.mju: debug